import type { Metadata } from 'next'
import { Lexend } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const lexend = Lexend({ subsets: ['latin'] })

import './globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lexend.className}>{children}</body>
    </html>
  )
}
