export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import TimelineStyles from "./timeline.module.css";
import { Newsreader, Nunito_Sans } from "next/font/google";

const newsreader = Newsreader({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${TimelineStyles.timelineContainer} ${newsreader.className} ${nunitoSans.className}`}
    >
      <body className="dark:bg-gray-950 dark:text-white">{children}</body>
    </html>
  );
}
